[project]
name = "dockerfile-generation-using-local-llms-beginner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arif", email = "arifuzzaman.badhon1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.2",
]

[project.scripts]
dockerfile-generation-using-local-llms-beginner = "dockerfile_generation_using_local_llms_beginner:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
